# -*- coding: utf-8 -*-
"""time series(&)text data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kM8ZyfkHEMHUxQS3yQTfxDYY5JXphij
"""

import pandas as pd
import matplotlib.pyplot as plt
data={
    "Date":pd.to_datetime(["2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01"]),
    "value":[10,15,22,28,35]
}
df = pd.DataFrame(data)
df.set_index("Date",inplace=True)
plt.figure(figsize=(10,6))
plt.plot(df.index,df["value"],marker='x')
plt.xlabel("data")
plt.ylabel("values")
plt.title("time series with thread")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data={
    "Date":pd.to_datetime(["2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01","2022-06-01","2022-07-01","2022-08-01","2022-09-01"]),
    "value":[10,15,22,28,35,12,14,31,34]
}
df = pd.DataFrame(data)
df.set_index("Date",inplace=True)
plt.figure(figsize=(10,6))
plt.plot(df.index,df["value"],marker='x')
plt.xlabel("data")
plt.ylabel("values")
plt.title("time series with seasonality")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter
text_data="ll the ocean buried Now are our house In the souls"
wordcloud=WordCloud(width=800,height=400,background_color='black').generate(text_data)
plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.title('wordcloud')
plt.axis('off')
plt.show()
words=text_data.split()
word_counts=Counter(words)
plt.figure(figsize=(10,5))
plt.bar(word_counts.keys(),word_counts.values())
plt.title('histogram of word frequencies')
plt.xlabel('words')
plt.ylabel('frequency')
plt.xticks(rotation=90)
plt.show